server {
    listen 3000;
    server_name localhost;
    port_in_redirect off;
    absolute_redirect off;
    root /usr/share/nginx/html;

    location /stayoneadmin {
        alias /usr/share/nginx/html/stayoneadmin;
        try_files $uri $uri/ /stayoneadmin/index.html;
    }

    location / {
        rewrite ^/$ /stayoneadmin permanent;
        try_files $uri $uri/ /stayoneadmin/index.html;
    }
}

